version: '3'
services:
  db1:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./:/docker-entrypoint-initdb.d/
